language: php

php:
    - "5.4"
    - "5.5"
    - "5.6"
    - "5.7"

script: "./vendor/bin/tester tests/ -c ./tests/php-unix.ini"

matrix:
    allow_failures:
        - php: 7.0

before_script:
    - composer self-update
    - composer install --prefer-source
    - mysql -e 'create database deaw_test'
    - cp ./tests/config/config.travis.neon ./tests/config/config.neon
    - cp ./tests/config/database.travis.ini ./tests/config/database.ini
